# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

# limit switch
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports collision_in]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports collision_out]


set_property PACKAGE_PIN U17 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports start]

set_property PACKAGE_PIN V3 [get_ports start_signal]
set_property IOSTANDARD LVCMOS33 [get_ports start_signal]

# uart channel
set_property PACKAGE_PIN B18 [get_ports rx]
set_property IOSTANDARD LVCMOS33 [get_ports rx]
set_property PACKAGE_PIN A18 [get_ports tx]
set_property IOSTANDARD LVCMOS33 [get_ports tx]

# Servo PWM output
set_property PACKAGE_PIN B16 [get_ports servo_pwm]
set_property IOSTANDARD LVCMOS33 [get_ports servo_pwm] 
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset] 

# Stepper Motor Top

set_property PACKAGE_PIN H1 [get_ports top_ENA]
set_property IOSTANDARD LVCMOS33 [get_ports top_ENA]
set_property PACKAGE_PIN K2 [get_ports top_ENB]
set_property IOSTANDARD LVCMOS33 [get_ports top_ENB]
set_property PACKAGE_PIN J1 [get_ports top_IN1]
set_property IOSTANDARD LVCMOS33 [get_ports top_IN1]
set_property PACKAGE_PIN L2 [get_ports top_IN2]
set_property IOSTANDARD LVCMOS33 [get_ports top_IN2]
set_property PACKAGE_PIN J2 [get_ports top_IN3]
set_property IOSTANDARD LVCMOS33 [get_ports top_IN3]
set_property PACKAGE_PIN G2 [get_ports top_IN4]
set_property IOSTANDARD LVCMOS33 [get_ports top_IN4]

# Stepper Motor Btm
set_property PACKAGE_PIN L17 [get_ports btm_ENA]
set_property IOSTANDARD LVCMOS33 [get_ports btm_ENA]
set_property PACKAGE_PIN M19 [get_ports btm_ENB]
set_property IOSTANDARD LVCMOS33 [get_ports btm_ENB]
set_property PACKAGE_PIN K17 [get_ports btm_IN1]
set_property IOSTANDARD LVCMOS33 [get_ports btm_IN1]
set_property PACKAGE_PIN M18 [get_ports btm_IN2]
set_property IOSTANDARD LVCMOS33 [get_ports btm_IN2]
set_property PACKAGE_PIN N17 [get_ports btm_IN3]
set_property IOSTANDARD LVCMOS33 [get_ports btm_IN3]
set_property PACKAGE_PIN P18 [get_ports btm_IN4]
set_property IOSTANDARD LVCMOS33 [get_ports btm_IN4]

# set_property PACKAGE_PIN U16 [get_ports led[0]]
# set_property IOSTANDARD LVCMOS33 [get_ports led[0]]  
# set_property PACKAGE_PIN E19 [get_ports led[1]] 
# set_property IOSTANDARD LVCMOS33 [get_ports led[1]]  
# set_property PACKAGE_PIN U19 [get_ports led[2]]
# set_property IOSTANDARD LVCMOS33 [get_ports led[2]]  
# set_property PACKAGE_PIN V19 [get_ports led[3]]
# set_property IOSTANDARD LVCMOS33 [get_ports led[3]]  
# set_property PACKAGE_PIN W18 [get_ports led[4]]
# set_property IOSTANDARD LVCMOS33 [get_ports led[4]]  
# set_property PACKAGE_PIN U15 [get_ports led[5]]
# set_property IOSTANDARD LVCMOS33 [get_ports led[5]]  
# set_property PACKAGE_PIN U14 [get_ports led[6]]
# set_property IOSTANDARD LVCMOS33 [get_ports led[6]]  
# set_property PACKAGE_PIN V14 [get_ports led[7]]
# set_property IOSTANDARD LVCMOS33 [get_ports led[7]]   

set_property PACKAGE_PIN W7 [get_ports {seg[6]}]
set_property PACKAGE_PIN W6 [get_ports {seg[5]}]
set_property PACKAGE_PIN U8 [get_ports {seg[4]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[2]}]
set_property PACKAGE_PIN V5 [get_ports {seg[1]}]
set_property PACKAGE_PIN U7 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

set_property PACKAGE_PIN W4 [get_ports {AN[3]}]
set_property PACKAGE_PIN V4 [get_ports {AN[2]}]
set_property PACKAGE_PIN U4 [get_ports {AN[1]}]
set_property PACKAGE_PIN U2 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]

set_property PACKAGE_PIN W19 [get_ports return_to_0]
set_property IOSTANDARD LVCMOS33 [get_ports return_to_0]